name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/mohlenhoff_alpha2
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha,format=short
          labels: |
            org.opencontainers.image.title=Möhlenhoff Alpha 2 Add-On
            org.opencontainers.image.description=Home Assistant add-on for integrating with Möhlenhoff Alpha 2 heating systems
            org.opencontainers.image.vendor=Home Assistant Add-ons
            org.opencontainers.image.licenses=MIT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./mohlenhoff_alpha2
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=https://github.com/${{ github.repository }}
            BUILD_VERSION=${{ steps.meta.outputs.version }}
            BUILD_NAME=Möhlenhoff Alpha 2 Integration
            BUILD_DESCRIPTION=Home Assistant add-on for integrating with Möhlenhoff Alpha 2 heating systems